### ISSUE TITLE
Möglichkeit anbieten, alle geschriebenen Funktionen immer zu importieren

### ISSUE THREAD

**Issue by greendayasd** [SSnake95/CM#42]
bei vielen kleinen Funktionen hast du die Funktion schneller selbst geschrieben, als sie eingebunden :D

**Comment by SSnake95** [comment]
1. Funktionen importieren klicken
2. Datei auswählen
3. Ok klicken

**Comment by greendayasd** [comment]
Momentan wenn du was brauchst musst du erst das Aktionsfenster schließen und zurück zum Hauptfenster, dann das Funktionsfenster öffnen, dann die richtigen Einstellungen machen, um das richtige Datenformat zu importieren, dann die Datei erst mal suchen, dann Ok klicken. Wenn viele Fkt hat, die man öfter benutzt, ist das eher umständlich
