### ISSUE TITLE
Klicks auf "Auslöser", "Aktion" und "Beschreibung" haben keine Wirkung

### ISSUE THREAD

**Issue by greendayasd** [SSnake95/CM#44]
Da man sie drücken kann, sollten sie auch was machen, sortieren wäre gut

**Comment by SSnake95** [comment]
Hatten bisher die Wirkung, dass die Spalten per Drag&Drop vertauscht werden konnten. Jetzt kann auch Sortiert werden

**Comment by SSnake95** [comment]
Hatten bisher die Wirkung, dass die Spalten per Drag&Drop vertauscht werden konnten. Jetzt kann auch Sortiert werden
