### ISSUE TITLE
Abfrage, falls Aktion bearbeitet wurde und abgebrochen wird

### ISSUE THREAD

**Issue by greendayasd** [SSnake95/CM#47]

**Comment by SSnake95** [comment]
was meinst du?

**Comment by greendayasd** [comment]
Falls eine Aktion geändert wurde und du nicht auf Ok sondern Abbrechen klickst, werden momentan alle Änderungen ohne Abfrage verworfen.

Ich schulde dir btw noch 6 Euro^^

**Comment by SSnake95** [comment]
verbessert.
