### ISSUE TITLE
Nutzereingabe anfordern

### ISSUE THREAD

**Issue by greendayasd** [SSnake95/CM#51]
Aktion, dass sich Editfeld öffnet, Eingabe des Nutzers wird in Variable gespeichert.
Hast du mir glaub ich schon mal gezeigt, findet man bei den Aktionen aber nicht

**Comment by SSnake95** [comment]
Lies dir die Dokumentation "Variablen und Konstanten" durch. %ask% gibt einen Wert zurück, der über eine Inputbox abgefragt wird.

Der Trick lautet also:
Set='$var0,%ask%';

**Comment by greendayasd** [comment]
hab ich mittlerweile ja gemacht ;) Aber die Werte generell nicht auswendig lernen zu müssen sondern irgendwo in ner Liste zu haben wäre praktisch
