### ISSUE TITLE
Website öffnen

### ISSUE THREAD

**Issue by greendayasd** [SSnake95/CM#55]
Angegebene Website im Standartbrowser öffnen

**Comment by SSnake95** [comment]
Man achte auf die genaue Wortwahl: Website LADEN. Die Seite soll nicht geöffnet werden sondern nur ein HTTP Request an den Server geschickt werden.
Website öffnen/Datei öffnen/Programm starten über Programm starten Aktion.

Ich sollte vielleicht an den Benennungen rumschrauben

**Comment by greendayasd** [comment]
Man achte auf die genaue Wortwahl: Website ÖFFNEN :P Also als zusätzlichen Button, s. Issue 56
