### ISSUE TITLE
Infobox nach Tastenkombination erscheint nicht

### ISSUE THREAD

**Issue by greendayasd** [SSnake95/CM#59]
Beim Ausführen einer kleinen Aktion mit Auslöser "Strg + D" erschien die Infobox rechts unten nach den ersten 2 Ausführungen, danach nicht mehr, auch nicht nach Stop/Start bzw Neustart der CM. Wann genau soll die Infobox angezeigt werden?

**Comment by greendayasd** [comment]
(im Log steht dazu nichts)

**Comment by SSnake95** [comment]
fehlerhafte Bedienung? Nicht reproduzierbar
