### ISSUE TITLE
Soll das Drücken einer Taste innerhalb einer Aktion weitere Aktionen in der CM auslösen?

### ISSUE THREAD

**Issue by greendayasd** [SSnake95/CM#60]
Das ist zumindest momentan nicht der Fall, aber vielleicht ist das ja auch gewollt, damit keine bösen Leute da ne Rekursion verursachen :)

**Comment by SSnake95** [comment]
Antwort: Die CM prüft nur im Leerlauf auf neue gedrückte Tasten. Die Warten-Aktion zählt auch als Leerlauf.
Funktioneren sollte also:

Tastehalten='B';
Warten='1';
Tasteloslassen='B';
(B ist der zweite Auslöser)

Und Ja, das ist, damit keine bösen Rekursionen entstehen ;)
