### ISSUE TITLE
Wenn Liste gespeichert werden soll, wird der "falsche" Speichername ausgewählt

### ISSUE THREAD

**Issue by greendayasd** [SSnake95/CM#67]
Bsp:
CM starten
Datei a.cml öffnen
als b.cml speichern, beim Speichern wird a.cml als Name vorgeschlagen
 (Window Name wird in b geändert)
wieder speichern, beim Speichern wird a.cml als Name vorgeschlagen, sollte b.cml sein

**Comment by SSnake95** [comment]
gefixt
