### ISSUE TITLE
Sehr hoher Ram Verbrauch

### ISSUE THREAD

**Issue by greendayasd** [SSnake95/CM#69]
Ich hatte grade 2 CMs offen und als eine abgestürzt ist und ich sie über den Taskmanager abschießen musste ist mir aufgefallen, dass die absgestürzte CM zwar nur ca 2k Ram verbraucht hat, die andere aber wie "damals" ca 200k

**Comment by SSnake95** [comment]
gefixt. jetzt ca 2,7 MB Ram
