### ISSUE TITLE
Haben Aktion-übergreifende Variablen nicht zwischenzeitlich funktioniert?

### ISSUE THREAD

**Issue by greendayasd** [SSnake95/CM#70]
Bsp:
Auslöser1:
Set='$var0,true';
Tastedrücken='Enter';
Warten='500';
Tastedrücken='Enter';
Warten='500';
If='$var0';
Jmp='2';

Auslöser2:
Set='$var0,false';

Auslöser 2 kann 1 nicht stoppen, auch nicht, wenn statt true und false   1 und 0 verwendet werden.

**Comment by SSnake95** [comment]
gefixt. Vor und nach "warten" werden die Variablen synchronisiert
