### ISSUE TITLE
Mit STRG + A alles im Aktionsfenster markieren funktioniert nicht, wenn eine Taste mit "A" belegt ist

### ISSUE THREAD

**Issue by greendayasd** [SSnake95/CM#75]
Es poppt dann nur das Beschreibungsfenster auf, aber es wird nichts markiert, auch wenn die CM inaktiv ist. Gleiches gilt schätzungsweise auch bei anderen Kombinationen

**Comment by SSnake95** [comment]
Leider falsch getippt :(
