### ISSUE TITLE
Aktionsbeschreibung wurde automatisch ausgefüllt

### ISSUE THREAD

**Issue by greendayasd** [SSnake95/CM#78]
Ich hab keine Ahnung, durch was (evtl durch das Verwenden von Strg + Linksklick als Auslöser? hab grade nicht wirklich Zeit zum Testen) wurde "CM-ACTION" als Beschreibung eingefügt.

**Comment by SSnake95** [comment]
Die Cheat Machine hat jetzt für Items und Aktionen ein eigenes Zwischenablageformat.
Per Strg+V wird die Zwischenablage somit nicht mehr aus Versehen ins Beschreibungsfeld eingefügt.
